import argparse


def parse_args() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="eulix_embed.py",
        description="Knowledge Base Embedding Generator (Python/PyTorch)",
        add_help=False,
    )
    sub = p.add_subparsers(dest="command")
    ep = sub.add_parser(
        "embed",
        help="Generate embeddings for knowledge base generated by eulix_parser (default)",
    )
    ep.add_argument(
        "-k",
        "--kb-path",
        default="knowledge_base.json",
        metavar="PATH",
        help="Path to knowledge base JSON  [default: knowledge_base.json]",
    )
    ep.add_argument(
        "-o",
        "--output",
        default="./embeddings",
        metavar="DIR",
        help="Output directory             [default: ./embeddings]",
    )
    ep.add_argument(
        "-m",
        "--model",
        default="sentence-transformers/all-MiniLM-L6-v2",
        metavar="NAME",
        help="HuggingFace model name",
    )
    ep.add_argument(
        "-e",
        "--engine",
        default="torch",
        choices=["torch", "onnx"],
        metavar="ENGINE",
        help="Inference engine: torch or onnx  [default: torch]",
    )
    ep.add_argument(
        "-d",
        "--device",
        default=None,
        metavar="DEVICE",
        help="cuda / mps / cpu             [default: auto]",
    )
    ep.add_argument(
        "-b",
        "--batch-size",
        type=int,
        default=None,
        metavar="N",
        help="Batch size                   [default: auto]",
    )
    ep.add_argument(
        "--max-chunk",
        type=int,
        default=2000,
        metavar="N",
        help="Max chunk chars              [default: 2000]",
    )
    ep.add_argument(
        "--quantize",
        action="store_true",
        help="SQ8 int8 quantization: 4x smaller embeddings.bin, ~1%% quality loss",
    )
    ep.add_argument(
        "--no-comments",
        action="store_true",
        help="Remove comments/docstrings/license headers from embedding and vidx bins",
    )
    ep.add_argument(
        "--save-json",
        action="store_true",
        help="Also write embeddings.json (enables graph edge streaming)",
    )
    ep.add_argument(
        "--debug", action="store_true", help="Print debug info during pipeline"
    )
    qp = sub.add_parser(
        "query", help="Generate embedding for a query string (one-shot)"
    )
    qp.add_argument(
        "-q", "--query", default="", metavar="TEXT", help="Query text to embed"
    )
    qp.add_argument(
        "-m",
        "--model",
        default="sentence-transformers/all-MiniLM-L6-v2",
        metavar="NAME",
        help="HuggingFace model name",
    )
    qp.add_argument(
        "-e",
        "--engine",
        default="torch",
        choices=["torch", "onnx"],
        metavar="ENGINE",
        help="Inference engine: torch or onnx  [default: torch]",
    )
    qp.add_argument(
        "-f",
        "--format",
        default="json",
        metavar="FMT",
        help="json | binary  [default: json]",
    )
    sp = sub.add_parser(
        "serve", help="Long-lived stdin/stdout embedding server (avoids model reload)"
    )
    sp.add_argument(
        "-m",
        "--model",
        default="sentence-transformers/all-MiniLM-L6-v2",
        metavar="NAME",
        help="HuggingFace model name  [default: all-MiniLM-L6-v2]",
    )
    sp.add_argument(
        "-e", "--engine",
        default="torch",
        choices=["torch", "onnx"],
        metavar="ENGINE",
        help="Inference engine: torch or onnx  [default: torch]",
    )
    sp.add_argument(
        "-d",
        "--device",
        default=None,
        metavar="DEVICE",
        help="cuda / mps / cpu  [default: auto]",
    )
    sp.add_argument(
        "-b",
        "--batch-size",
        type=int,
        default=None,
        metavar="N",
        help="Batch size for 'queries' requests  [default: auto]",
    )
    cp = sub.add_parser("compare", help="Compare embeddings.bin with vectors.bin")
    cp.add_argument("emb", nargs="?", default="embeddings/embeddings.bin")
    cp.add_argument("vec", nargs="?", default="embeddings/vectors.bin")
    sub.add_parser("ijson-backend", help="Report active ijson C-backend")
    vp = sub.add_parser("version", help="Print version information")
    vp.add_argument("--short", action="store_true", help="Print only version number")

    return p
